-- @description Advanced Solo Bundle
-- @author zaibuyidao
-- @version 1.0.2
-- @changelog
--   # Fixed the "attempt to index a nil value" issue.
-- @links
--   Forum Thread https://forum.cockos.com/showthread.php?t=290856
--   GitHub repository https://github.com/zaibuyidao/ReaScripts
-- @metapackage
-- @provides
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Item from Edit Cursor.lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Item from First Selected Item.lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Item from Mouse Position.lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Item Without Moving Edit Cursor.lua
--   [main=main,midi_editor] Advanced Solo/zaibuyidao_Hold to Solo MIDI Item from Edit Cursor.lua
--   [main=main,midi_editor] Advanced Solo/zaibuyidao_Hold to Solo MIDI Item from Mouse Position.lua
--   [main=midi_editor] Advanced Solo/zaibuyidao_Hold to Solo Note from Edit Cursor.lua
--   [main=midi_editor] Advanced Solo/zaibuyidao_Hold to Solo Note from Mouse Position.lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Track from Edit Cursor (Exclude Item Selection).lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Track from Edit Cursor.lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Track from Mouse Position (Exclude Item Selection).lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Track from Mouse Position.lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Track Without Moving Edit Cursor (Exclude Item Selection).lua
--   [main=main] Advanced Solo/zaibuyidao_Hold to Solo Track Without Moving Edit Cursor.lua
--   [main=main] Advanced Solo/zaibuyidao_Instant Solo Item from Edit Cursor.lua
--   [main=main] Advanced Solo/zaibuyidao_Instant Solo Item from First Selected Item.lua
--   [main=main] Advanced Solo/zaibuyidao_Instant Solo Item from Mouse Position.lua
--   [main=main,midi_editor] Advanced Solo/zaibuyidao_Instant Solo MIDI Item from Edit Cursor.lua
--   [main=main,midi_editor] Advanced Solo/zaibuyidao_Instant Solo MIDI Item from Mouse Position.lua
--   [main=midi_editor] Advanced Solo/zaibuyidao_Instant Solo Note from Edit Cursor.lua
--   [main=midi_editor] Advanced Solo/zaibuyidao_Instant Solo Note from Mouse Position.lua
--   [main=main] Advanced Solo/zaibuyidao_Instant Solo Track from Edit Cursor.lua
--   [main=main] Advanced Solo/zaibuyidao_Instant Solo Track from Mouse Position.lua
--   [main=main] Advanced Solo/zaibuyidao_Toggle Solo Automatically for Selected Tracks.lua
--   [main=main] Advanced Solo/zaibuyidao_Toggle Solo for Selected Tracks or Track Under Mouse.lua
--   [main=main] Advanced Solo/zaibuyidao_Toggle Solo for Selected Tracks.lua
--   [main=main,midi_editor] Advanced Solo/zaibuyidao_Toggle Solo for Specific Track (Settings).lua
--   [main=main,midi_editor] Advanced Solo/zaibuyidao_Toggle Solo for Specific Track.lua
--   [nomain] Advanced Solo/lib/*.cur
--   [nomain] Advanced Solo/lib/serpent.lua
-- @donation http://www.paypal.me/zaibuyidao
-- @about
--   Intelligent SOLO Script Series, filter "zaibuyidao solo" in ReaPack or Actions to access all scripts.
--   Requires JS_ReaScriptAPI & SWS Extension

-- Licensed under the GNU GPL v3