-- @description Articulation Map Bundle
-- @author zaibuyidao
-- @version 1.0.1
-- @changelog
--   + New Script
-- @links
--   https://forum.cockos.com/showthread.php?t=289373
--   https://github.com/zaibuyidao/ReaScripts
-- @metapackage
-- @provides
--   [main=midi_editor] Articulation Map/zaibuyidao_Articulation Map - No GUI.lua
--   [main=midi_editor] Articulation Map/zaibuyidao_Articulation Map - Note To PC.lua
--   [main=midi_editor] Articulation Map/zaibuyidao_Articulation Map - PC To Note.lua
--   [main=midi_editor] Articulation Map/zaibuyidao_Articulation Map - Toggle Note PC.lua
--   [main=midi_editor] Articulation Map/zaibuyidao_Articulation Map.lua
--   [nomain] Articulation Map/lib/*.lua
--   Articulation Map/articulation_map_factory.reabank
--  [jsfx] Articulation Map/jsfx/articulation_map.jsfx
--  [jsfx] Articulation Map/jsfx/pre_trigger_cc_event.jsfx
-- @donation http://www.paypal.me/zaibuyidao
-- @about Requires JS_ReaScriptAPI & SWS Extension

-- Licensed under the GNU GPL v3