-- @description SFX Tag Search Bundle
-- @author zaibuyidao
-- @version 1.0.4
-- @changelog Initial release
-- @reference
--   https://forum.cockos.com/showthread.php?t=229807
-- @links
--   https://www.soundengine.cn/user/%E5%86%8D%E8%A3%9C%E4%B8%80%E5%88%80
--   https://github.com/zaibuyidao/ReaScripts
-- @metapackage
-- @provides
--   [main] SFX/zaibuyidao_SFX Tag Search.lua
--   [nomain] SFX/lib/config.lua
--   [nomain] SFX/lib/core.lua
--   [nomain] SFX/lib/LIP.lua
--   [nomain] SFX/lib/ListView.lua
--   [nomain] SFX/lib/reaper-utils.lua
--   [nomain] SFX/lib/REQ/*.lua
--   SFX/*.csv
-- @donation http://www.paypal.me/zaibuyidao
-- @about Requires JS_ReaScriptAPI & SWS Extension

-- Licensed under the GNU GPL v3