-- @description SFX Tag Search Bundle
-- @author zaibuyidao
-- @version 1.0
-- @changelog Initial release
-- @reference
--   https://forum.cockos.com/showthread.php?t=229807
-- @links
--   https://www.soundengine.cn/user/%E5%86%8D%E8%A3%9C%E4%B8%80%E5%88%80
--   https://github.com/zaibuyidao/ReaScripts
-- @metapackage
-- @provides
--   [main] SFX/zaibuyidao_SFX Tag Search.lua
--   [nomain] SFX/config.lua
--   [nomain] SFX/core.lua
--   [nomain] SFX/LIP.lua
--   [nomain] SFX/ListView.lua
--   [nomain] SFX/reaper-utils.lua
--   [nomain] SFX/REQ/*.lua
--   SFX/*.csv
-- @donation http://www.paypal.me/zaibuyidao
-- @about Requires JS_ReaScriptAPI

-- Licensed under the GNU GPL v3