-- @description Soundmole
-- @author zaibuyidao
-- @version 1.0.70
-- @changelog
--   Added Mono, Stereo, 4.0 (Quad), 5.0 (Surround), and 5.1 (Surround + LFE) routing options with automatic output channel switching during preview.
--   Other detailed improvements and bug fixes.
-- @reference
--   https://forum.cockos.com/showthread.php?t=300916
-- @links
--   https://www.soundengine.cn/u/zaibuyidao
--   https://github.com/zaibuyidao/ReaScripts
-- @metapackage
-- @provides
--   [main=main] Soundmole/zaibuyidao_Soundmole.lua
--   [nomain] Soundmole/lib/*.lua
--   Soundmole/data/*.csv
--   Soundmole/data/icons.otf
--   Soundmole/data/odrf_upr_regular.otf
-- @donation http://www.paypal.me/zaibuyidao
-- @about Requires JS_ReaScriptAPI & SWS Extension

-- Licensed under the GNU GPL v3