-- @description Soundmole
-- @author zaibuyidao
-- @version 1.0.159
-- @changelog
--   Added ability to jump to the same folder or filter in Database mode by clicking the album art.
--   Added ability to remember the selected sidebar tab state upon exit.
--   Fixed an issue where recent searches could not be saved to Saved Searches.
--   Fixed "Reset to Defaults" not restoring all settings.
--   Fixed image loading issues and stability, added support for WAV embedded ID3 artwork.
--   Fixed an issue where peak meter channel settings were not saving correctly.
--   Enabled the "Search on Enter" option by default.
--   Support reaper_soundmole-x64.dll v0.0.11
-- @reference
--   https://forum.cockos.com/showthread.php?t=300916
-- @links
--   https://www.soundengine.cn/u/zaibuyidao
--   https://github.com/zaibuyidao/ReaScripts
-- @metapackage
-- @provides
--   [main=main] Soundmole/zaibuyidao_Soundmole.lua
--   [main=main] Soundmole/zaibuyidao_Soundmole - Add Selected Files to Target Database.lua
--   [nomain] Soundmole/lib/*.lua
--   [nomain] Soundmole/lib/*.py
--   [nomain] Soundmole/lib/*.cur
--   Soundmole/lang/*.txt
--   Soundmole/data/*.csv
--   Soundmole/data/icons.otf
--   Soundmole/data/icons-regular.otf
--   Soundmole/data/odrf_upr_regular.otf
-- @donation http://www.paypal.me/zaibuyidao
-- @about Requires JS_ReaScriptAPI & SWS Extension

-- Licensed under the GNU GPL v3