-- @description UCS Tag Search Rename Bundle
-- @version 1.0
-- @author zaibuyidao
-- @links
--   https://www.soundengine.cn/user/%E5%86%8D%E8%A3%9C%E4%B8%80%E5%88%80
--   https://github.com/zaibuyidao/ReaScripts
-- @provides
--   [main] UCS/zaibuyidao_UCS Tag Rename.lua
--   [main] UCS/zaibuyidao_UCS Tag Search.lua
--   [nomain] UCS/lib/*.lua
--   UCS/*.csv
-- @donation http://www.paypal.me/zaibuyidao
-- @about Requires JS_ReaScriptAPI

-- Licensed under the GNU GPL v3